// Code generated by "stringer -type=LEDState ledstates.go"; DO NOT EDIT.

package leds

import "strconv"

const _LEDState_name = "UnknownOffAlertOn"

var _LEDState_index = [...]uint8{0, 7, 10, 15, 17}

func (i LEDState) String() string {
	if i < 0 || i >= LEDState(len(_LEDState_index)-1) {
		return "LEDState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LEDState_name[_LEDState_index[i]:_LEDState_index[i+1]]
}
