// Code generated by "stringer -output leds_string.go -type=State leds_types.go"; DO NOT EDIT.

package leds

import "strconv"

const (
	_State_name_0 = "UnknownOffAlertOn"
	_State_name_1 = "testState"
)

var (
	_State_index_0 = [...]uint8{0, 7, 10, 15, 17}
)

func (i State) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _State_name_0[_State_index_0[i]:_State_index_0[i+1]]
	case i == 255:
		return _State_name_1
	default:
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
